### ISSUE TITLE
run ios failed 

### ISSUE THREAD

**Issue by JamestheDon** [ayooby/react-native-calendar-heatmap#17]
Metro bundler is unable to find the main module '/lib/src/CalendarHeatmap.js
link to repo:
https://github.com/JamestheDon/react-native-heatmap

<img width="408" alt="Screen Shot 2020-03-21 at 2 50 46 PM" src="https://user-images.githubusercontent.com/5084962/77237241-9d2bc280-6b83-11ea-88b1-064912e2721b.png">

tried removing node modules and reinstalling to no effect.

any help would be welcomed. :)

**Comment by WrathChaos** [comment]
Can you show me your package.json?

**Comment by kuraydev** [comment]
Can you try the example? https://github.com/ayooby/react-native-calendar-heatmap/tree/master/example

**Comment by JamestheDon** [comment]
The example ended up crashing as well.. 

I havent tried clearing the metro bundler cache though. 

<img width="488" alt="Screen Shot 2020-03-21 at 3 46 56 PM" src="https://user-images.githubusercontent.com/5084962/77238175-3f9b7400-6b8b-11ea-96d6-c5b1dcf21285.png">

**Comment by kuraydev** [comment]
I'm fixing it :)

**Comment by kuraydev** [comment]
Okay, I fixed it. However, @ayooby need to re-publish the new version. Until he does it, you can check the working version with my own npm release: 
```
npm i @freakycoder/react-native-calendar-heatmap
```
Also, fixed many bugs and updated the example with a fresh one :)
@JamestheDon can you try the new one?

**Comment by JamestheDon** [comment]
working on it! Build is still failing. For some reason Example doesnt want to open in simulator now.

<img width="943" alt="Screen Shot 2020-03-22 at 8 18 45 AM" src="https://user-images.githubusercontent.com/5084962/77253148-c5640180-6c15-11ea-8d9f-c3784688b0cc.png">


<img width="695" alt="Screen Shot 2020-03-22 at 8 07 33 AM" src="https://user-images.githubusercontent.com/5084962/77253014-fd1e7980-6c14-11ea-990e-39fbebd01db6.png">
<img width="505" alt="Screen Shot 2020-03-22 at 8 13 42 AM" src="https://user-images.githubusercontent.com/5084962/77253031-13c4d080-6c15-11ea-840a-e0c6d46d1d64.png">

**Comment by JamestheDon** [comment]
I also Init'ed a new proj and isntalled your updated pkg. 
Ran into this: 
<img width="405" alt="Screen Shot 2020-03-22 at 8 29 28 AM" src="https://user-images.githubusercontent.com/5084962/77253432-643d2d80-6c17-11ea-80c2-245a3edccf74.png">

**Comment by kuraydev** [comment]
@JamestheDon You should follow these steps: 
* clone the project
* cd example
* npm i
* cd ios
* pod install && cd .. 
* watchman watch-del-all && rm -rf node_modules/ && npm cache clean -f && npm install && react-native run-ios 

It should work, I've tested it.

**Comment by JamestheDon** [comment]
Thanks @WrathChaos, that did it!

**Comment by kuraydev** [comment]
Awesome :) If you have another problem please feel free to open another issue.
